version: '3'
services:
  node:
    build: ./docker/node
    volumes:
      - .:/var/www/html
    command: sh -c "cd src && npm start"
    ports:
      - 3000:3000
  gcloud:
    image: google/cloud-sdk:latest
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html/src
    tty: true
